version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: make circleci
      - run: make docs-html
      - store_artifacts:
          path: docs/_build/html
          destination: docs
